---
when:
  - event: push
    branch: main
    path:
      include:
        - .woodpecker/deploy.yaml
        - packages/zones/data/**.yaml
        - "**/package.json"
        - "**/*.ts"

steps:
  - name: build
    image: node:24-alpine
    commands:
      - corepack enable
      - pnpm install
      - pnpm run --recursive --filter @domains/config... build

  - name: deploy
    image: stackexchange/dnscontrol:4.30.0
    environment:
      CREDS_JSON:
        from_secret: DNSCONTROL_CREDS_JSON
    commands:
      - cd config/dist/
      - printf '%s' "$${CREDS_JSON}" > creds.json
      - dnscontrol push
